comment test workflow
Co-authored-by: rafaortegano <rortegano@fi.uba.ar>

diff --git a/.github/workflows/format-and-lint.yaml b/.github/workflows/format-and-lint.yaml
--- a/.github/workflows/format-and-lint.yaml
+++ b/.github/workflows/format-and-lint.yaml
@@ -32,44 +32,44 @@ jobs:
       - name: Run Pylint
         run: pylint app/
 
-  test:
-    name: Run Tests
-    runs-on: ubuntu-latest
-    needs: lint-and-format
+  # test:
+  #   name: Run Tests
+  #   runs-on: ubuntu-latest
+  #   needs: lint-and-format
     
-    steps:
-      - uses: actions/checkout@v3
+  #   steps:
+  #     - uses: actions/checkout@v3
       
-      - name: Set up Docker Buildx
-        uses: docker/setup-buildx-action@v2
+  #     - name: Set up Docker Buildx
+  #       uses: docker/setup-buildx-action@v2
       
-      - name: Run tests with Docker Compose
-        run: |
-          # Create a directory for coverage data
-          mkdir -p coverage
-          chmod 777 coverage
+  #     - name: Run tests with Docker Compose
+  #       run: |
+  #         # Create a directory for coverage data
+  #         mkdir -p coverage
+  #         chmod 777 coverage
           
-          # Run tests with Docker Compose
-          docker compose -f docker-compose.test.yml up --build --abort-on-container-exit --exit-code-from app-test
+  #         # Run tests with Docker Compose
+  #         docker compose -f docker-compose.test.yml up --build --abort-on-container-exit --exit-code-from app-test
           
-          # Check if coverage.xml exists
-          if [ ! -f coverage/coverage.xml ]; then
-            echo "Coverage file not found!"
-            exit 1
-          fi
+  #         # Check if coverage.xml exists
+  #         if [ ! -f coverage/coverage.xml ]; then
+  #           echo "Coverage file not found!"
+  #           exit 1
+  #         fi
       
-      - name: Upload coverage to Coveralls
-        uses: coverallsapp/github-action@v2
-        with:
-          github-token: ${{ secrets.GITHUB_TOKEN }}
-          file: coverage/coverage.xml
+  #     - name: Upload coverage to Coveralls
+  #       uses: coverallsapp/github-action@v2
+  #       with:
+  #         github-token: ${{ secrets.GITHUB_TOKEN }}
+  #         file: coverage/coverage.xml
       
-      - name: Upload coverage to Codecov
-        uses: codecov/codecov-action@v3
-        with:
-          files: ./coverage/coverage.xml
-          fail_ci_if_error: false
+  #     - name: Upload coverage to Codecov
+  #       uses: codecov/codecov-action@v3
+  #       with:
+  #         files: ./coverage/coverage.xml
+  #         fail_ci_if_error: false
       
-      - name: Clean up Docker resources
-        if: always()
-        run: docker compose -f docker-compose.test.yml down -v
+  #     - name: Clean up Docker resources
+  #       if: always()
+  #       run: docker compose -f docker-compose.test.yml down -v
